### PR TITLE
Add typescript definition file

### LINKED ISSUE #10: Add Typescript types
Hi Robert,

I created a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60800) in DefinitelyTyped to create the Typescript types for the library.

Feel free to review it!

### PR DESCRIPTION
**Pull request by yannbriancon**
Fix #10

### CODE REVIEW

**Comment by infusion** [comment]
Great work again, thanks!

**Comment by yannbriancon** [comment]
@infusion Do you think you will have time to deploy a new version to npm soon?

I really need this fromMatrix method 😄

**Comment by infusion** [comment]
yes, on my way ;)

**Comment by yannbriancon** [comment]
Thanks Robert!

**Comment by infusion** [comment]
v1.4 just landed :-) Thanks for using Quaternion.js!!

**Pull request merged**
